# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/dfd_builder
spring.datasource.username=postgres
spring.datasource.password=Ganesh@24

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SERVER
server.port=8080