server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:dfd_builder
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
  mail:
    host: localhost
    port: 587
    username: test
    password: test

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

file:
  upload-dir: uploads/
